application: alertbirds
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.3"

handlers:
- url: /static/images
  static_dir: static/images
- url: /static/css
  static_dir: static/css
- url: /static/js
  static_dir: static/js
- url: /static/sounds
  static_dir: static/sounds
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico 
- url: /cron/.*
  script: alertbirds.application
  login: admin
- url: /
  script: alertbirds.application
  secure: always
- url: /.*
  script: alertbirds.application
  login: required
  secure: always
